---
abstract: 'Perl modules MRUIZ likes to use'
author:
  - 'Miquel Ruiz <mruiz@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-MRUIZ
requires:
  Carp::Always: 0
  DBI: 0
  Data::Dump: 0
  DateTime: 0
  DateTime::Format::Strptime: 0
  Dist::Zilla: 0
  Dist::Zilla::Plugin::CopyReadmeFromBuild: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::PluginBundle::GitHub: 0
  File::Slurp: 0
  Getopt::Long: 0
  HTTP::Tiny: 0.014
  JSON: 0
  JSON::XS: 0
  Moo: 0
  Moose: 0
  Mozilla::CA: 0
  Net::SSLeay: 0
  Path::Class: 0
  Test::Exception: 0
  Test::More: 0
  Try::Tiny: 0
  URI: 0
  YAML: 0
resources:
  bugtracker: https://github.com/miquelruiz/Task-BeLike-MRUIZ/issues
  repository: git://github.com/miquelruiz/Task-BeLike-MRUIZ.git
version: 0.01
